apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nq3y6uff3-java-quarkus
  janus-idp.io/tekton: nq3y6uff3-java-quarkus
  backstage.io/kubernetes-id: nq3y6uff3-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nq3y6uff3-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
